/* tslint:disable */
/* eslint-disable */
/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BadRequest } from '../models';
// @ts-ignore
import { Caption } from '../models';
// @ts-ignore
import { CaptionsListResponse } from '../models';
// @ts-ignore
import { CaptionsUpdatePayload } from '../models';
// @ts-ignore
import { CaptionsUploadPayload } from '../models';
// @ts-ignore
import { NotFound } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * CaptionsApi - axios parameter creator
 * @export
 */
export const CaptionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Delete a caption in a specific language by by video id.
         * @summary Delete a caption
         * @param {string} videoId The unique identifier for the video you want to delete a caption from.
         * @param {string} language A valid language identifier using IETF language tags. You can use primary subtags like &#x60;en&#x60; (English), extended subtags like &#x60;fr-CA&#x60; (French, Canada), or region subtags like &#x60;zh-Hans-CN&#x60; (Simplified Chinese used in the PRC).  - This parameter **only accepts dashes for separators**, for example &#x60;fr-CA&#x60;. If you use a different separator in your request, the API returns an error. - When the value in your request does not match any covered language, the API returns an error. - You can find the list of supported tags [here](https://docs.api.video/vod/add-captions#supported-caption-language-tags).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteByLanguage: async (videoId: string, language: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'videoId' is not null or undefined
            assertParamExists('deleteByLanguage', 'videoId', videoId)
            // verify required parameter 'language' is not null or undefined
            assertParamExists('deleteByLanguage', 'language', language)
            const localVarPath = `/videos/{videoId}/captions/{language}`
                .replace(`{${"videoId"}}`, encodeURIComponent(String(videoId !== undefined ? videoId : `-videoId-`)))
                .replace(`{${"language"}}`, encodeURIComponent(String(language !== undefined ? language : `-language-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/videos/{videoId}/captions/{language}',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a caption for a video in a specific language.
         * @summary Retrieve a caption
         * @param {string} videoId The unique identifier for the video you want captions for.
         * @param {string} language A valid language identifier using IETF language tags. You can use primary subtags like &#x60;en&#x60; (English), extended subtags like &#x60;fr-CA&#x60; (French, Canada), or region subtags like &#x60;zh-Hans-CN&#x60; (Simplified Chinese used in the PRC).  - This parameter **only accepts dashes for separators**, for example &#x60;fr-CA&#x60;. If you use a different separator in your request, the API returns an error. - When the value in your request does not match any covered language, the API returns an error. - You can find the list of supported tags [here](https://docs.api.video/vod/add-captions#supported-caption-language-tags).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByLanguage: async (videoId: string, language: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'videoId' is not null or undefined
            assertParamExists('getByLanguage', 'videoId', videoId)
            // verify required parameter 'language' is not null or undefined
            assertParamExists('getByLanguage', 'language', language)
            const localVarPath = `/videos/{videoId}/captions/{language}`
                .replace(`{${"videoId"}}`, encodeURIComponent(String(videoId !== undefined ? videoId : `-videoId-`)))
                .replace(`{${"language"}}`, encodeURIComponent(String(language !== undefined ? language : `-language-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/videos/{videoId}/captions/{language}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a list of available captions by video id.
         * @summary List video captions
         * @param {string} videoId The unique identifier for the video you want to retrieve a list of captions for.
         * @param {number} [currentPage] Choose the number of search results to return per page. Minimum value: 1
         * @param {number} [pageSize] Results per page. Allowed values 1-100, default is 25.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listByVideoId: async (videoId: string, currentPage?: number, pageSize?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'videoId' is not null or undefined
            assertParamExists('listByVideoId', 'videoId', videoId)
            const localVarPath = `/videos/{videoId}/captions`
                .replace(`{${"videoId"}}`, encodeURIComponent(String(videoId !== undefined ? videoId : `-videoId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)
            if (currentPage !== undefined) {
                localVarQueryParameter['currentPage'] = currentPage;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/videos/{videoId}/captions',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update caption settings.
         * @summary Update a caption
         * @param {string} videoId The unique identifier for the video you want to have automatic captions for.
         * @param {string} language A valid language identifier using IETF language tags. You can use primary subtags like &#x60;en&#x60; (English), extended subtags like &#x60;fr-CA&#x60; (French, Canada), or region subtags like &#x60;zh-Hans-CN&#x60; (Simplified Chinese used in the PRC).  - This parameter **only accepts dashes for separators**, for example &#x60;fr-CA&#x60;. If you use a different separator in your request, the API returns an error. - When the value in your request does not match any covered language, the API returns an error. - You can find the list of supported tags [here](https://docs.api.video/vod/add-captions#supported-caption-language-tags).
         * @param {CaptionsUpdatePayload} captionsUpdatePayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSettings: async (videoId: string, language: string, captionsUpdatePayload: CaptionsUpdatePayload, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'videoId' is not null or undefined
            assertParamExists('updateSettings', 'videoId', videoId)
            // verify required parameter 'language' is not null or undefined
            assertParamExists('updateSettings', 'language', language)
            // verify required parameter 'captionsUpdatePayload' is not null or undefined
            assertParamExists('updateSettings', 'captionsUpdatePayload', captionsUpdatePayload)
            const localVarPath = `/videos/{videoId}/captions/{language}`
                .replace(`{${"videoId"}}`, encodeURIComponent(String(videoId !== undefined ? videoId : `-videoId-`)))
                .replace(`{${"language"}}`, encodeURIComponent(String(language !== undefined ? language : `-language-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: captionsUpdatePayload,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/videos/{videoId}/captions/{language}',
                httpMethod: 'PATCH'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(captionsUpdatePayload, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Upload a VTT file to add captions to your video. More information can be found [here](https://docs.api.video/vod/add-captions)
         * @summary Upload a caption
         * @param {string} videoId The unique identifier for the video you want to add a caption to.
         * @param {string} language A valid language identifier using IETF language tags. You can use primary subtags like &#x60;en&#x60; (English), extended subtags like &#x60;fr-CA&#x60; (French, Canada), or region subtags like &#x60;zh-Hans-CN&#x60; (Simplified Chinese used in the PRC).  - This parameter **only accepts dashes for separators**, for example &#x60;fr-CA&#x60;. If you use a different separator in your request, the API returns an error. - When the value in your request does not match any covered language, the API returns an error. - You can find the list of supported tags [here](https://docs.api.video/vod/add-captions#supported-caption-language-tags).
         * @param {Uint8Array | File | buffer.File} file The video text track (VTT) you want to upload.
         * @param {CaptionsUploadPayload} captionsUploadPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadVttFile: async (videoId: string, language: string, file: Uint8Array | File | buffer.File, captionsUploadPayload: CaptionsUploadPayload, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'videoId' is not null or undefined
            assertParamExists('uploadVttFile', 'videoId', videoId)
            // verify required parameter 'language' is not null or undefined
            assertParamExists('uploadVttFile', 'language', language)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadVttFile', 'file', file)
            // verify required parameter 'captionsUploadPayload' is not null or undefined
            assertParamExists('uploadVttFile', 'captionsUploadPayload', captionsUploadPayload)
            const localVarPath = `/videos/{videoId}/captions/{language}`
                .replace(`{${"videoId"}}`, encodeURIComponent(String(videoId !== undefined ? videoId : `-videoId-`)))
                .replace(`{${"language"}}`, encodeURIComponent(String(language !== undefined ? language : `-language-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();
            const addFormParam = async (name: string, data: any, isBinary: boolean, isPrimitiveType: boolean) => {
                if (isBinary) {
                    if (data instanceof Uint8Array) {
                        // Handle Buffer data
                        const filetype = await fromBuffer(data)
                        const filename = filetype === undefined ? name : `${name}.${filetype.ext}`
                        localVarFormParams.append(name, data as any, filename);
                    } else if ("name" in data) {
                        // File instances in browsers and Node.js have the
                        // "name" property "Duck typing" files to handle browser
                        // File class or Node.js File class
                        // Web: https://developer.mozilla.org/en-US/docs/Web/API/File
                        // Node.js: https://nodejs.org/api/buffer.html#new-bufferfilesources-filename-options
                        if (isBrowser()) {
                            // FormData in browser can accept File/Blob directly
                            localVarFormParams.append(name, data, data.name);
                        } else {
                            // FormData in Node.js can only accept raw Buffer so convert before passing
                            const bytes = await data.arrayBuffer()
                            const buffer = Buffer.from(bytes)
                            localVarFormParams.append(name, buffer, data.name);
                        }
                    }
                } else {
                    if (isPrimitiveType) {
                        /**
                         * FormData can only accept string or Blob so we need to convert
                         * non-string primitives to string. We also need to convert
                         */
                        if (typeof data === "object") {
                          localVarFormParams.append(name, JSON.stringify(data));
                        } else {
                          localVarFormParams.append(name, data);
                        }
                    } else {
                        if (isBrowser()) {
                            localVarFormParams.append(name, new Blob([JSON.stringify(data)], { type: "application/json" }))
                        } else {
                            localVarFormParams.append(name, JSON.stringify(data), { type: "application/json", filename: "data.json" });
                        }
                    }
                }
            }
            if (!isBrowser()) Object.assign(localVarHeaderParameter, localVarFormParams.getHeaders());

            // authentication apiKey required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (file !== undefined) {
                await addFormParam('file', file, true, true)
            }
    
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;
            requestBeforeHook({
                requestBody: captionsUploadPayload,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/videos/{videoId}/captions/{language}',
                httpMethod: 'POST'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CaptionsApi - functional programming interface
 * @export
 */
export const CaptionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CaptionsApiAxiosParamCreator(configuration)
    return {
        /**
         * Delete a caption in a specific language by by video id.
         * @summary Delete a caption
         * @param {CaptionsApiDeleteByLanguageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteByLanguage(requestParameters: CaptionsApiDeleteByLanguageRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteByLanguage(requestParameters.videoId, requestParameters.language, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Retrieve a caption for a video in a specific language.
         * @summary Retrieve a caption
         * @param {CaptionsApiGetByLanguageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getByLanguage(requestParameters: CaptionsApiGetByLanguageRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Caption>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getByLanguage(requestParameters.videoId, requestParameters.language, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Retrieve a list of available captions by video id.
         * @summary List video captions
         * @param {CaptionsApiListByVideoIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listByVideoId(requestParameters: CaptionsApiListByVideoIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CaptionsListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listByVideoId(requestParameters.videoId, requestParameters.currentPage, requestParameters.pageSize, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Update caption settings.
         * @summary Update a caption
         * @param {CaptionsApiUpdateSettingsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSettings(requestParameters: CaptionsApiUpdateSettingsRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Caption>> {
            const captionsUpdatePayload: CaptionsUpdatePayload = {
                default: requestParameters.default
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSettings(requestParameters.videoId, requestParameters.language, captionsUpdatePayload, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Upload a VTT file to add captions to your video. More information can be found [here](https://docs.api.video/vod/add-captions)
         * @summary Upload a caption
         * @param {CaptionsApiUploadVttFileRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadVttFile(requestParameters: CaptionsApiUploadVttFileRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Caption>> {
            const captionsUploadPayload: CaptionsUploadPayload = {
                file: requestParameters.file
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadVttFile(requestParameters.videoId, requestParameters.language, requestParameters.file, captionsUploadPayload, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CaptionsApi - factory interface
 * @export
 */
export const CaptionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CaptionsApiFp(configuration)
    return {
        /**
         * Delete a caption in a specific language by by video id.
         * @summary Delete a caption
         * @param {CaptionsApiDeleteByLanguageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteByLanguage(requestParameters: CaptionsApiDeleteByLanguageRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteByLanguage(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a caption for a video in a specific language.
         * @summary Retrieve a caption
         * @param {CaptionsApiGetByLanguageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByLanguage(requestParameters: CaptionsApiGetByLanguageRequest, options?: AxiosRequestConfig): AxiosPromise<Caption> {
            return localVarFp.getByLanguage(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a list of available captions by video id.
         * @summary List video captions
         * @param {CaptionsApiListByVideoIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listByVideoId(requestParameters: CaptionsApiListByVideoIdRequest, options?: AxiosRequestConfig): AxiosPromise<CaptionsListResponse> {
            return localVarFp.listByVideoId(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Update caption settings.
         * @summary Update a caption
         * @param {CaptionsApiUpdateSettingsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSettings(requestParameters: CaptionsApiUpdateSettingsRequest, options?: AxiosRequestConfig): AxiosPromise<Caption> {
            return localVarFp.updateSettings(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Upload a VTT file to add captions to your video. More information can be found [here](https://docs.api.video/vod/add-captions)
         * @summary Upload a caption
         * @param {CaptionsApiUploadVttFileRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadVttFile(requestParameters: CaptionsApiUploadVttFileRequest, options?: AxiosRequestConfig): AxiosPromise<Caption> {
            return localVarFp.uploadVttFile(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for deleteByLanguage operation in CaptionsApi.
 * @export
 * @interface CaptionsApiDeleteByLanguageRequest
 */
export type CaptionsApiDeleteByLanguageRequest = {
    
    /**
    * The unique identifier for the video you want to delete a caption from.
    * @type {string}
    * @memberof CaptionsApiDeleteByLanguage
    */
    readonly videoId: string
    
    /**
    * A valid language identifier using IETF language tags. You can use primary subtags like `en` (English), extended subtags like `fr-CA` (French, Canada), or region subtags like `zh-Hans-CN` (Simplified Chinese used in the PRC).  - This parameter **only accepts dashes for separators**, for example `fr-CA`. If you use a different separator in your request, the API returns an error. - When the value in your request does not match any covered language, the API returns an error. - You can find the list of supported tags [here](https://docs.api.video/vod/add-captions#supported-caption-language-tags).
    * @type {string}
    * @memberof CaptionsApiDeleteByLanguage
    */
    readonly language: string
    
}

/**
 * Request parameters for getByLanguage operation in CaptionsApi.
 * @export
 * @interface CaptionsApiGetByLanguageRequest
 */
export type CaptionsApiGetByLanguageRequest = {
    
    /**
    * The unique identifier for the video you want captions for.
    * @type {string}
    * @memberof CaptionsApiGetByLanguage
    */
    readonly videoId: string
    
    /**
    * A valid language identifier using IETF language tags. You can use primary subtags like `en` (English), extended subtags like `fr-CA` (French, Canada), or region subtags like `zh-Hans-CN` (Simplified Chinese used in the PRC).  - This parameter **only accepts dashes for separators**, for example `fr-CA`. If you use a different separator in your request, the API returns an error. - When the value in your request does not match any covered language, the API returns an error. - You can find the list of supported tags [here](https://docs.api.video/vod/add-captions#supported-caption-language-tags).
    * @type {string}
    * @memberof CaptionsApiGetByLanguage
    */
    readonly language: string
    
}

/**
 * Request parameters for listByVideoId operation in CaptionsApi.
 * @export
 * @interface CaptionsApiListByVideoIdRequest
 */
export type CaptionsApiListByVideoIdRequest = {
    
    /**
    * The unique identifier for the video you want to retrieve a list of captions for.
    * @type {string}
    * @memberof CaptionsApiListByVideoId
    */
    readonly videoId: string
    
    /**
    * Choose the number of search results to return per page. Minimum value: 1
    * @type {number}
    * @memberof CaptionsApiListByVideoId
    */
    readonly currentPage?: number
    
    /**
    * Results per page. Allowed values 1-100, default is 25.
    * @type {number}
    * @memberof CaptionsApiListByVideoId
    */
    readonly pageSize?: number
    
}

/**
 * Request parameters for updateSettings operation in CaptionsApi.
 * @export
 * @interface CaptionsApiUpdateSettingsRequest
 */
export type CaptionsApiUpdateSettingsRequest = {
    
    /**
    * The unique identifier for the video you want to have automatic captions for.
    * @type {string}
    * @memberof CaptionsApiUpdateSettings
    */
    readonly videoId: string
    
    /**
    * A valid language identifier using IETF language tags. You can use primary subtags like `en` (English), extended subtags like `fr-CA` (French, Canada), or region subtags like `zh-Hans-CN` (Simplified Chinese used in the PRC).  - This parameter **only accepts dashes for separators**, for example `fr-CA`. If you use a different separator in your request, the API returns an error. - When the value in your request does not match any covered language, the API returns an error. - You can find the list of supported tags [here](https://docs.api.video/vod/add-captions#supported-caption-language-tags).
    * @type {string}
    * @memberof CaptionsApiUpdateSettings
    */
    readonly language: string
    
} & CaptionsUpdatePayload

/**
 * Request parameters for uploadVttFile operation in CaptionsApi.
 * @export
 * @interface CaptionsApiUploadVttFileRequest
 */
export type CaptionsApiUploadVttFileRequest = {
    
    /**
    * The unique identifier for the video you want to add a caption to.
    * @type {string}
    * @memberof CaptionsApiUploadVttFile
    */
    readonly videoId: string
    
    /**
    * A valid language identifier using IETF language tags. You can use primary subtags like `en` (English), extended subtags like `fr-CA` (French, Canada), or region subtags like `zh-Hans-CN` (Simplified Chinese used in the PRC).  - This parameter **only accepts dashes for separators**, for example `fr-CA`. If you use a different separator in your request, the API returns an error. - When the value in your request does not match any covered language, the API returns an error. - You can find the list of supported tags [here](https://docs.api.video/vod/add-captions#supported-caption-language-tags).
    * @type {string}
    * @memberof CaptionsApiUploadVttFile
    */
    readonly language: string
    
    /**
    * The video text track (VTT) you want to upload.
    * @type {Uint8Array | File | buffer.File}
    * @memberof CaptionsApiUploadVttFile
    */
    readonly file: Uint8Array | File | buffer.File
    
} & CaptionsUploadPayload

/**
 * CaptionsApiGenerated - object-oriented interface
 * @export
 * @class CaptionsApiGenerated
 * @extends {BaseAPI}
 */
export class CaptionsApiGenerated extends BaseAPI {
    /**
     * Delete a caption in a specific language by by video id.
     * @summary Delete a caption
     * @param {CaptionsApiDeleteByLanguageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CaptionsApiGenerated
     */
    public deleteByLanguage(requestParameters: CaptionsApiDeleteByLanguageRequest, options?: AxiosRequestConfig) {
        return CaptionsApiFp(this.configuration).deleteByLanguage(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a caption for a video in a specific language.
     * @summary Retrieve a caption
     * @param {CaptionsApiGetByLanguageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CaptionsApiGenerated
     */
    public getByLanguage(requestParameters: CaptionsApiGetByLanguageRequest, options?: AxiosRequestConfig) {
        return CaptionsApiFp(this.configuration).getByLanguage(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a list of available captions by video id.
     * @summary List video captions
     * @param {CaptionsApiListByVideoIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CaptionsApiGenerated
     */
    public listByVideoId(requestParameters: CaptionsApiListByVideoIdRequest, options?: AxiosRequestConfig) {
        return CaptionsApiFp(this.configuration).listByVideoId(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update caption settings.
     * @summary Update a caption
     * @param {CaptionsApiUpdateSettingsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CaptionsApiGenerated
     */
    public updateSettings(requestParameters: CaptionsApiUpdateSettingsRequest, options?: AxiosRequestConfig) {
        return CaptionsApiFp(this.configuration).updateSettings(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Upload a VTT file to add captions to your video. More information can be found [here](https://docs.api.video/vod/add-captions)
     * @summary Upload a caption
     * @param {CaptionsApiUploadVttFileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CaptionsApiGenerated
     */
    public uploadVttFile(requestParameters: CaptionsApiUploadVttFileRequest, options?: AxiosRequestConfig) {
        return CaptionsApiFp(this.configuration).uploadVttFile(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
