/* tslint:disable */
/* eslint-disable */
/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BadRequest } from '../models';
// @ts-ignore
import { Chapter } from '../models';
// @ts-ignore
import { ChaptersListResponse } from '../models';
// @ts-ignore
import { ChaptersUpdatePayload } from '../models';
// @ts-ignore
import { NotFound } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ChaptersApi - axios parameter creator
 * @export
 */
export const ChaptersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Delete a chapter in a specific language by providing the video ID for the video you want to delete the chapter from and the language the chapter is in.
         * @summary Delete a chapter
         * @param {string} videoId The unique identifier for the video you want to delete a chapter from.
         * @param {string} language A valid [BCP 47](https://github.com/libyal/libfwnt/wiki/Language-Code-identifiers) language representation.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteChapterInLanguage: async (videoId: string, language: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'videoId' is not null or undefined
            assertParamExists('deleteChapterInLanguage', 'videoId', videoId)
            // verify required parameter 'language' is not null or undefined
            assertParamExists('deleteChapterInLanguage', 'language', language)
            const localVarPath = `/videos/{videoId}/chapters/{language}`
                .replace(`{${"videoId"}}`, encodeURIComponent(String(videoId !== undefined ? videoId : `-videoId-`)))
                .replace(`{${"language"}}`, encodeURIComponent(String(language !== undefined ? language : `-language-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/videos/{videoId}/chapters/{language}',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a chapter for by video id in a specific language. 
         * @summary Retrieve a chapter
         * @param {string} videoId The unique identifier for the video you want to show a chapter for.
         * @param {string} language A valid [BCP 47](https://github.com/libyal/libfwnt/wiki/Language-Code-identifiers) language representation.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChapterByLanguage: async (videoId: string, language: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'videoId' is not null or undefined
            assertParamExists('getChapterByLanguage', 'videoId', videoId)
            // verify required parameter 'language' is not null or undefined
            assertParamExists('getChapterByLanguage', 'language', language)
            const localVarPath = `/videos/{videoId}/chapters/{language}`
                .replace(`{${"videoId"}}`, encodeURIComponent(String(videoId !== undefined ? videoId : `-videoId-`)))
                .replace(`{${"language"}}`, encodeURIComponent(String(language !== undefined ? language : `-language-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/videos/{videoId}/chapters/{language}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a list of all chapters for by video id.
         * @summary List video chapters
         * @param {string} videoId The unique identifier for the video you want to retrieve a list of chapters for.
         * @param {number} [currentPage] Choose the number of search results to return per page. Minimum value: 1
         * @param {number} [pageSize] Results per page. Allowed values 1-100, default is 25.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listByVideo: async (videoId: string, currentPage?: number, pageSize?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'videoId' is not null or undefined
            assertParamExists('listByVideo', 'videoId', videoId)
            const localVarPath = `/videos/{videoId}/chapters`
                .replace(`{${"videoId"}}`, encodeURIComponent(String(videoId !== undefined ? videoId : `-videoId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)
            if (currentPage !== undefined) {
                localVarQueryParameter['currentPage'] = currentPage;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/videos/{videoId}/chapters',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Upload a VTT file to add chapters to your video. Chapters help break the video into sections. Read our [tutorial](https://api.video/blog/tutorials/adding-chapters-to-your-videos/) for more details.
         * @summary Upload a chapter
         * @param {string} videoId The unique identifier for the video you want to upload a chapter for.
         * @param {string} language A valid [BCP 47](https://github.com/libyal/libfwnt/wiki/Language-Code-identifiers) language representation.
         * @param {Uint8Array | File | buffer.File} file The VTT file describing the chapters you want to upload.
         * @param {ChaptersUpdatePayload} chaptersUpdatePayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadVttFile: async (videoId: string, language: string, file: Uint8Array | File | buffer.File, chaptersUpdatePayload: ChaptersUpdatePayload, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'videoId' is not null or undefined
            assertParamExists('uploadVttFile', 'videoId', videoId)
            // verify required parameter 'language' is not null or undefined
            assertParamExists('uploadVttFile', 'language', language)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadVttFile', 'file', file)
            // verify required parameter 'chaptersUpdatePayload' is not null or undefined
            assertParamExists('uploadVttFile', 'chaptersUpdatePayload', chaptersUpdatePayload)
            const localVarPath = `/videos/{videoId}/chapters/{language}`
                .replace(`{${"videoId"}}`, encodeURIComponent(String(videoId !== undefined ? videoId : `-videoId-`)))
                .replace(`{${"language"}}`, encodeURIComponent(String(language !== undefined ? language : `-language-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();
            const addFormParam = async (name: string, data: any, isBinary: boolean, isPrimitiveType: boolean) => {
                if (isBinary) {
                    if (data instanceof Uint8Array) {
                        // Handle Buffer data
                        const filetype = await fromBuffer(data)
                        const filename = filetype === undefined ? name : `${name}.${filetype.ext}`
                        localVarFormParams.append(name, data as any, filename);
                    } else if ("name" in data) {
                        // File instances in browsers and Node.js have the
                        // "name" property "Duck typing" files to handle browser
                        // File class or Node.js File class
                        // Web: https://developer.mozilla.org/en-US/docs/Web/API/File
                        // Node.js: https://nodejs.org/api/buffer.html#new-bufferfilesources-filename-options
                        if (isBrowser()) {
                            // FormData in browser can accept File/Blob directly
                            localVarFormParams.append(name, data, data.name);
                        } else {
                            // FormData in Node.js can only accept raw Buffer so convert before passing
                            const bytes = await data.arrayBuffer()
                            const buffer = Buffer.from(bytes)
                            localVarFormParams.append(name, buffer, data.name);
                        }
                    }
                } else {
                    if (isPrimitiveType) {
                        /**
                         * FormData can only accept string or Blob so we need to convert
                         * non-string primitives to string. We also need to convert
                         */
                        if (typeof data === "object") {
                          localVarFormParams.append(name, JSON.stringify(data));
                        } else {
                          localVarFormParams.append(name, data);
                        }
                    } else {
                        if (isBrowser()) {
                            localVarFormParams.append(name, new Blob([JSON.stringify(data)], { type: "application/json" }))
                        } else {
                            localVarFormParams.append(name, JSON.stringify(data), { type: "application/json", filename: "data.json" });
                        }
                    }
                }
            }
            if (!isBrowser()) Object.assign(localVarHeaderParameter, localVarFormParams.getHeaders());

            // authentication apiKey required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (file !== undefined) {
                await addFormParam('file', file, true, true)
            }
    
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;
            requestBeforeHook({
                requestBody: chaptersUpdatePayload,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/videos/{videoId}/chapters/{language}',
                httpMethod: 'POST'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChaptersApi - functional programming interface
 * @export
 */
export const ChaptersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ChaptersApiAxiosParamCreator(configuration)
    return {
        /**
         * Delete a chapter in a specific language by providing the video ID for the video you want to delete the chapter from and the language the chapter is in.
         * @summary Delete a chapter
         * @param {ChaptersApiDeleteChapterInLanguageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteChapterInLanguage(requestParameters: ChaptersApiDeleteChapterInLanguageRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteChapterInLanguage(requestParameters.videoId, requestParameters.language, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Retrieve a chapter for by video id in a specific language. 
         * @summary Retrieve a chapter
         * @param {ChaptersApiGetChapterByLanguageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getChapterByLanguage(requestParameters: ChaptersApiGetChapterByLanguageRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Chapter>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getChapterByLanguage(requestParameters.videoId, requestParameters.language, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Retrieve a list of all chapters for by video id.
         * @summary List video chapters
         * @param {ChaptersApiListByVideoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listByVideo(requestParameters: ChaptersApiListByVideoRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChaptersListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listByVideo(requestParameters.videoId, requestParameters.currentPage, requestParameters.pageSize, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Upload a VTT file to add chapters to your video. Chapters help break the video into sections. Read our [tutorial](https://api.video/blog/tutorials/adding-chapters-to-your-videos/) for more details.
         * @summary Upload a chapter
         * @param {ChaptersApiUploadVttFileRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadVttFile(requestParameters: ChaptersApiUploadVttFileRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Chapter>> {
            const chaptersUpdatePayload: ChaptersUpdatePayload = {
                file: requestParameters.file
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadVttFile(requestParameters.videoId, requestParameters.language, requestParameters.file, chaptersUpdatePayload, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ChaptersApi - factory interface
 * @export
 */
export const ChaptersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ChaptersApiFp(configuration)
    return {
        /**
         * Delete a chapter in a specific language by providing the video ID for the video you want to delete the chapter from and the language the chapter is in.
         * @summary Delete a chapter
         * @param {ChaptersApiDeleteChapterInLanguageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteChapterInLanguage(requestParameters: ChaptersApiDeleteChapterInLanguageRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteChapterInLanguage(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a chapter for by video id in a specific language. 
         * @summary Retrieve a chapter
         * @param {ChaptersApiGetChapterByLanguageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChapterByLanguage(requestParameters: ChaptersApiGetChapterByLanguageRequest, options?: AxiosRequestConfig): AxiosPromise<Chapter> {
            return localVarFp.getChapterByLanguage(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a list of all chapters for by video id.
         * @summary List video chapters
         * @param {ChaptersApiListByVideoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listByVideo(requestParameters: ChaptersApiListByVideoRequest, options?: AxiosRequestConfig): AxiosPromise<ChaptersListResponse> {
            return localVarFp.listByVideo(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Upload a VTT file to add chapters to your video. Chapters help break the video into sections. Read our [tutorial](https://api.video/blog/tutorials/adding-chapters-to-your-videos/) for more details.
         * @summary Upload a chapter
         * @param {ChaptersApiUploadVttFileRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadVttFile(requestParameters: ChaptersApiUploadVttFileRequest, options?: AxiosRequestConfig): AxiosPromise<Chapter> {
            return localVarFp.uploadVttFile(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for deleteChapterInLanguage operation in ChaptersApi.
 * @export
 * @interface ChaptersApiDeleteChapterInLanguageRequest
 */
export type ChaptersApiDeleteChapterInLanguageRequest = {
    
    /**
    * The unique identifier for the video you want to delete a chapter from.
    * @type {string}
    * @memberof ChaptersApiDeleteChapterInLanguage
    */
    readonly videoId: string
    
    /**
    * A valid [BCP 47](https://github.com/libyal/libfwnt/wiki/Language-Code-identifiers) language representation.
    * @type {string}
    * @memberof ChaptersApiDeleteChapterInLanguage
    */
    readonly language: string
    
}

/**
 * Request parameters for getChapterByLanguage operation in ChaptersApi.
 * @export
 * @interface ChaptersApiGetChapterByLanguageRequest
 */
export type ChaptersApiGetChapterByLanguageRequest = {
    
    /**
    * The unique identifier for the video you want to show a chapter for.
    * @type {string}
    * @memberof ChaptersApiGetChapterByLanguage
    */
    readonly videoId: string
    
    /**
    * A valid [BCP 47](https://github.com/libyal/libfwnt/wiki/Language-Code-identifiers) language representation.
    * @type {string}
    * @memberof ChaptersApiGetChapterByLanguage
    */
    readonly language: string
    
}

/**
 * Request parameters for listByVideo operation in ChaptersApi.
 * @export
 * @interface ChaptersApiListByVideoRequest
 */
export type ChaptersApiListByVideoRequest = {
    
    /**
    * The unique identifier for the video you want to retrieve a list of chapters for.
    * @type {string}
    * @memberof ChaptersApiListByVideo
    */
    readonly videoId: string
    
    /**
    * Choose the number of search results to return per page. Minimum value: 1
    * @type {number}
    * @memberof ChaptersApiListByVideo
    */
    readonly currentPage?: number
    
    /**
    * Results per page. Allowed values 1-100, default is 25.
    * @type {number}
    * @memberof ChaptersApiListByVideo
    */
    readonly pageSize?: number
    
}

/**
 * Request parameters for uploadVttFile operation in ChaptersApi.
 * @export
 * @interface ChaptersApiUploadVttFileRequest
 */
export type ChaptersApiUploadVttFileRequest = {
    
    /**
    * The unique identifier for the video you want to upload a chapter for.
    * @type {string}
    * @memberof ChaptersApiUploadVttFile
    */
    readonly videoId: string
    
    /**
    * A valid [BCP 47](https://github.com/libyal/libfwnt/wiki/Language-Code-identifiers) language representation.
    * @type {string}
    * @memberof ChaptersApiUploadVttFile
    */
    readonly language: string
    
    /**
    * The VTT file describing the chapters you want to upload.
    * @type {Uint8Array | File | buffer.File}
    * @memberof ChaptersApiUploadVttFile
    */
    readonly file: Uint8Array | File | buffer.File
    
} & ChaptersUpdatePayload

/**
 * ChaptersApiGenerated - object-oriented interface
 * @export
 * @class ChaptersApiGenerated
 * @extends {BaseAPI}
 */
export class ChaptersApiGenerated extends BaseAPI {
    /**
     * Delete a chapter in a specific language by providing the video ID for the video you want to delete the chapter from and the language the chapter is in.
     * @summary Delete a chapter
     * @param {ChaptersApiDeleteChapterInLanguageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChaptersApiGenerated
     */
    public deleteChapterInLanguage(requestParameters: ChaptersApiDeleteChapterInLanguageRequest, options?: AxiosRequestConfig) {
        return ChaptersApiFp(this.configuration).deleteChapterInLanguage(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a chapter for by video id in a specific language. 
     * @summary Retrieve a chapter
     * @param {ChaptersApiGetChapterByLanguageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChaptersApiGenerated
     */
    public getChapterByLanguage(requestParameters: ChaptersApiGetChapterByLanguageRequest, options?: AxiosRequestConfig) {
        return ChaptersApiFp(this.configuration).getChapterByLanguage(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a list of all chapters for by video id.
     * @summary List video chapters
     * @param {ChaptersApiListByVideoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChaptersApiGenerated
     */
    public listByVideo(requestParameters: ChaptersApiListByVideoRequest, options?: AxiosRequestConfig) {
        return ChaptersApiFp(this.configuration).listByVideo(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Upload a VTT file to add chapters to your video. Chapters help break the video into sections. Read our [tutorial](https://api.video/blog/tutorials/adding-chapters-to-your-videos/) for more details.
     * @summary Upload a chapter
     * @param {ChaptersApiUploadVttFileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChaptersApiGenerated
     */
    public uploadVttFile(requestParameters: ChaptersApiUploadVttFileRequest, options?: AxiosRequestConfig) {
        return ChaptersApiFp(this.configuration).uploadVttFile(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
