/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AccessToken
 */
export interface AccessToken {
    /**
     * The access token containing security credentials allowing you to acccess the API. The token lasts for one hour.
     * @type {string}
     * @memberof AccessToken
     */
    'access_token'?: string;
    /**
     * The type of token you have.
     * @type {string}
     * @memberof AccessToken
     */
    'token_type'?: string;
    /**
     * A token you can use to get the next access token when your current access token expires.
     * @type {string}
     * @memberof AccessToken
     */
    'refresh_token'?: string;
    /**
     * Lists the time in seconds when your access token expires. It lasts for one hour.
     * @type {number}
     * @memberof AccessToken
     */
    'expires_in'?: number;
}

