/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnalyticsData } from './analytics-data';
import { Pagination } from './pagination';

/**
 * 
 * @export
 * @interface AnalyticsPlaysResponse
 */
export interface AnalyticsPlaysResponse {
    /**
     * 
     * @type {Array<AnalyticsData>}
     * @memberof AnalyticsPlaysResponse
     */
    'data': Array<AnalyticsData>;
    /**
     * 
     * @type {Pagination}
     * @memberof AnalyticsPlaysResponse
     */
    'pagination': Pagination;
}

