/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AnalyticsData
 */
export interface AnalyticsData {
    /**
     * Shows a value for the property you have specified for `dimension` in your request. For example, if you requested `dimension=videoId`, each `value` field in the response returns a different videoId.
     * @type {string}
     * @memberof AnalyticsData
     */
    'value': string;
    /**
     * Shows the number of play events for one specific `value`.
     * @type {number}
     * @memberof AnalyticsData
     */
    'plays': number;
}

