/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AuthenticatePayload
 */
export interface AuthenticatePayload {
    /**
     * Your account API key. You can use your sandbox API key, or you can use your production API key.
     * @type {string}
     * @memberof AuthenticatePayload
     */
    'apiKey': string;
}

