/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AdditionalBadRequestErrors } from './additional-bad-request-errors';

/**
 * 
 * @export
 * @interface BadRequest
 */
export interface BadRequest {
    /**
     * A description of the error that occurred.
     * @type {string}
     * @memberof BadRequest
     */
    'title'?: string;
    /**
     * A link to the error documentation.
     * @type {string}
     * @memberof BadRequest
     */
    'type'?: string;
    /**
     * The name of the parameter that caused the error.
     * @type {string}
     * @memberof BadRequest
     */
    'name'?: string;
    /**
     * The HTTP status code.
     * @type {number}
     * @memberof BadRequest
     */
    'status'?: number;
    /**
     * Returns any additional problems in the request in an array of objects.
     * @type {Set<AdditionalBadRequestErrors>}
     * @memberof BadRequest
     */
    'problems'?: Set<AdditionalBadRequestErrors>;
}

