/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BytesRange
 */
export interface BytesRange {
    /**
     * The starting point for the range of bytes for a chunk of a video.
     * @type {number}
     * @memberof BytesRange
     */
    'from'?: number;
    /**
     * The ending point for the range of bytes for a chunk of a video.
     * @type {number}
     * @memberof BytesRange
     */
    'to'?: number;
    /**
     * The total number of expected bytes.
     * @type {number}
     * @memberof BytesRange
     */
    'total'?: number;
}

