/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Caption } from './caption';
import { Pagination } from './pagination';

/**
 * 
 * @export
 * @interface CaptionsListResponse
 */
export interface CaptionsListResponse {
    /**
     * 
     * @type {Array<Caption>}
     * @memberof CaptionsListResponse
     */
    'data': Array<Caption>;
    /**
     * 
     * @type {Pagination}
     * @memberof CaptionsListResponse
     */
    'pagination': Pagination;
}

