/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Caption
 */
export interface Caption {
    /**
     * The unique resource identifier of the uploaded caption.
     * @type {string}
     * @memberof Caption
     */
    'uri'?: string;
    /**
     * A direct URL to the uploaded caption file.
     * @type {string}
     * @memberof Caption
     */
    'src'?: string;
    /**
     * Indicates the language of the uploaded caption file using IETF language tags.
     * @type {string}
     * @memberof Caption
     */
    'srclang'?: string;
    /**
     * Returns the native name of the caption language in UTF-8 encoding.
     * @type {string}
     * @memberof Caption
     */
    'languageName'?: string;
    /**
     * Whether you will have subtitles or not. True for yes you will have subtitles, false for no you will not have subtitles.
     * @type {boolean}
     * @memberof Caption
     */
    'default'?: boolean;
}

