/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Chapter
 */
export interface Chapter {
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    'uri'?: string;
    /**
     * The link to your VTT file, which contains your chapters information for the video.
     * @type {string}
     * @memberof Chapter
     */
    'src'?: string;
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    'language'?: string;
}

