/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LiveStreamSessionClient } from './live-stream-session-client';
import { LiveStreamSessionDevice } from './live-stream-session-device';
import { LiveStreamSessionLocation } from './live-stream-session-location';
import { LiveStreamSessionReferrer } from './live-stream-session-referrer';
import { LiveStreamSessionSession } from './live-stream-session-session';
import { VideoSessionOs } from './video-session-os';

/**
 * 
 * @export
 * @interface LiveStreamSession
 */
export interface LiveStreamSession {
    /**
     * 
     * @type {LiveStreamSessionSession}
     * @memberof LiveStreamSession
     */
    'session'?: LiveStreamSessionSession;
    /**
     * 
     * @type {LiveStreamSessionLocation}
     * @memberof LiveStreamSession
     */
    'location'?: LiveStreamSessionLocation;
    /**
     * 
     * @type {LiveStreamSessionReferrer}
     * @memberof LiveStreamSession
     */
    'referrer'?: LiveStreamSessionReferrer;
    /**
     * 
     * @type {LiveStreamSessionDevice}
     * @memberof LiveStreamSession
     */
    'device'?: LiveStreamSessionDevice;
    /**
     * 
     * @type {VideoSessionOs}
     * @memberof LiveStreamSession
     */
    'os'?: VideoSessionOs;
    /**
     * 
     * @type {LiveStreamSessionClient}
     * @memberof LiveStreamSession
     */
    'client'?: LiveStreamSessionClient;
}

