/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LiveStreamAssets } from './live-stream-assets';
import { RestreamsResponseObject } from './restreams-response-object';

/**
 * 
 * @export
 * @interface LiveStream
 */
export interface LiveStream {
    /**
     * The unique identifier for the live stream. Live stream IDs begin with \"li.\"
     * @type {string}
     * @memberof LiveStream
     */
    'liveStreamId': string;
    /**
     * The name of your live stream.
     * @type {string}
     * @memberof LiveStream
     */
    'name'?: string;
    /**
     * The unique, private stream key that you use to begin streaming.
     * @type {string}
     * @memberof LiveStream
     */
    'streamKey'?: string;
    /**
     * Whether your video can be viewed by everyone, or requires authentication to see it. A setting of false will require a unique token for each view. Learn more about the Private Video feature [here](https://docs.api.video/delivery-analytics/video-privacy-access-management).
     * @type {boolean}
     * @memberof LiveStream
     */
    'public'?: boolean;
    /**
     * 
     * @type {LiveStreamAssets}
     * @memberof LiveStream
     */
    'assets'?: LiveStreamAssets;
    /**
     * The unique identifier for the player.
     * @type {string}
     * @memberof LiveStream
     */
    'playerId'?: string;
    /**
     * Whether or not you are broadcasting the live video you recorded for others to see. True means you are broadcasting to viewers, false means you are not.
     * @type {boolean}
     * @memberof LiveStream
     */
    'broadcasting'?: boolean;
    /**
     * Returns the list of RTMP restream destinations.
     * @type {Array<RestreamsResponseObject>}
     * @memberof LiveStream
     */
    'restreams': Array<RestreamsResponseObject>;
    /**
     * When the player was created, presented in ISO-8601 format.
     * @type {string}
     * @memberof LiveStream
     */
    'createdAt'?: string;
    /**
     * When the player was last updated, presented in ISO-8601 format.
     * @type {string}
     * @memberof LiveStream
     */
    'updatedAt'?: string;
}

