/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RestreamsRequestObject } from './restreams-request-object';

/**
 * 
 * @export
 * @interface LiveStreamCreationPayload
 */
export interface LiveStreamCreationPayload {
    /**
     * Add a name for your live stream here.
     * @type {string}
     * @memberof LiveStreamCreationPayload
     */
    'name': string;
    /**
     * Whether your video can be viewed by everyone, or requires authentication to see it. A setting of false will require a unique token for each view. Learn more about the Private Video feature [here](https://docs.api.video/delivery-analytics/video-privacy-access-management).
     * @type {boolean}
     * @memberof LiveStreamCreationPayload
     */
    'public'?: boolean;
    /**
     * The unique identifier for the player.
     * @type {string}
     * @memberof LiveStreamCreationPayload
     */
    'playerId'?: string;
    /**
     * Use this parameter to add, edit, or remove RTMP services where you want to restream a live stream. The list can only contain up to 5 destinations.
     * @type {Array<RestreamsRequestObject>}
     * @memberof LiveStreamCreationPayload
     */
    'restreams'?: Array<RestreamsRequestObject>;
}

