/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LiveStreamSessionReferrer
 */
export interface LiveStreamSessionReferrer {
    /**
     * The website the viewer of the live stream was referred to in order to view the live stream.
     * @type {string}
     * @memberof LiveStreamSessionReferrer
     */
    'url'?: string;
    /**
     * The type of search that brought the viewer to the live stream. Organic would be they found it on their own, paid would be they found it via an advertisement.
     * @type {string}
     * @memberof LiveStreamSessionReferrer
     */
    'medium'?: string;
    /**
     * Where the viewer came from to see the live stream (usually where they searched from).
     * @type {string}
     * @memberof LiveStreamSessionReferrer
     */
    'source'?: string;
    /**
     * What term they searched for that led them to the live stream.
     * @type {string}
     * @memberof LiveStreamSessionReferrer
     */
    'searchTerm'?: string;
}

