/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LiveStreamAssets
 */
export interface LiveStreamAssets {
    /**
     * The http live streaming (HLS) link for your live video stream.
     * @type {string}
     * @memberof LiveStreamAssets
     */
    'hls'?: string;
    /**
     * The embed code for the iframe containing your live video stream.
     * @type {string}
     * @memberof LiveStreamAssets
     */
    'iframe'?: string;
    /**
     * A link to the video player that is playing your live stream.
     * @type {string}
     * @memberof LiveStreamAssets
     */
    'player'?: string;
    /**
     * A link to the thumbnail for your video.
     * @type {string}
     * @memberof LiveStreamAssets
     */
    'thumbnail'?: string;
}

