/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LiveStreamSessionSession
 */
export interface LiveStreamSessionSession {
    /**
     * A unique identifier for your session. You can use this to track what happens during a specific session.
     * @type {string}
     * @memberof LiveStreamSessionSession
     */
    'sessionId'?: string;
    /**
     * When the session started, with the date and time presented in ISO-8601 format.
     * @type {string}
     * @memberof LiveStreamSessionSession
     */
    'loadedAt'?: string;
    /**
     * When the session ended, with the date and time presented in ISO-8601 format.
     * @type {string}
     * @memberof LiveStreamSessionSession
     */
    'endedAt'?: string;
}

