/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RestreamsRequestObject } from './restreams-request-object';

/**
 * 
 * @export
 * @interface LiveStreamUpdatePayload
 */
export interface LiveStreamUpdatePayload {
    /**
     * The name you want to use for your live stream.
     * @type {string}
     * @memberof LiveStreamUpdatePayload
     */
    'name'?: string;
    /**
     * Whether your video can be viewed by everyone, or requires authentication to see it. A setting of false will require a unique token for each view. Learn more about the Private Video feature [here](https://docs.api.video/delivery-analytics/video-privacy-access-management).
     * @type {boolean}
     * @memberof LiveStreamUpdatePayload
     */
    'public'?: boolean;
    /**
     * The unique ID for the player associated with a live stream that you want to update.
     * @type {string}
     * @memberof LiveStreamUpdatePayload
     */
    'playerId'?: string;
    /**
     * Use this parameter to add, edit, or remove RTMP services where you want to restream a live stream. The list can only contain up to 5 destinations. This operation updates all restream destinations in the same request. If you do not want to modify an existing restream destination, you need to include it in your request, otherwise it is removed.
     * @type {Array<RestreamsRequestObject>}
     * @memberof LiveStreamUpdatePayload
     */
    'restreams'?: Array<RestreamsRequestObject>;
}

