/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * What kind of browser the viewer is using for the live stream session.
 * @export
 * @interface LiveStreamSessionClient
 */
export interface LiveStreamSessionClient {
    /**
     * The version of the browser used to view the live stream session.
     * @type {string}
     * @memberof LiveStreamSessionClient
     */
    'version'?: string;
    /**
     * The name of the browser used to view the live stream session.
     * @type {string}
     * @memberof LiveStreamSessionClient
     */
    'name'?: string;
    /**
     * The type of client used to view the live stream session.
     * @type {string}
     * @memberof LiveStreamSessionClient
     */
    'type'?: string;
}

