/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Metadata
 */
export interface Metadata {
    /**
     * The constant that defines the data set.
     * @type {string}
     * @memberof Metadata
     */
    'key'?: string;
    /**
     * A variable which belongs to the data set.
     * @type {string}
     * @memberof Metadata
     */
    'value'?: string;
}

