/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface NotFound
 */
export interface NotFound {
    /**
     * 
     * @type {string}
     * @memberof NotFound
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotFound
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotFound
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof NotFound
     */
    'status'?: number;
}

