/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaginationLink } from './pagination-link';

/**
 * 
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * Total number of items that exist.
     * @type {number}
     * @memberof Pagination
     */
    'itemsTotal'?: number;
    /**
     * Number of items listed in the current page.
     * @type {number}
     * @memberof Pagination
     */
    'pagesTotal'?: number;
    /**
     * Maximum number of item per page.
     * @type {number}
     * @memberof Pagination
     */
    'pageSize'?: number;
    /**
     * The current page index.
     * @type {number}
     * @memberof Pagination
     */
    'currentPage'?: number;
    /**
     * The number of items on the current page.
     * @type {number}
     * @memberof Pagination
     */
    'currentPageItems'?: number;
    /**
     * 
     * @type {Array<PaginationLink>}
     * @memberof Pagination
     */
    'links': Array<PaginationLink>;
}

