/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PlayerThemeUploadLogoPayload
 */
export interface PlayerThemeUploadLogoPayload {
    /**
     * The name of the file you want to use for your logo.
     * @type {Uint8Array | File | buffer.File}
     * @memberof PlayerThemeUploadLogoPayload
     */
    'file': Uint8Array | File | buffer.File;
    /**
     * A public link that you want to advertise in your player. For example, you could add a link to your company. When a viewer clicks on your logo, they will be taken to this address.
     * @type {string}
     * @memberof PlayerThemeUploadLogoPayload
     */
    'link'?: string;
}

