/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PlayerThemeCreationPayload
 */
export interface PlayerThemeCreationPayload {
    /**
     * Add a name for your player theme here.
     * @type {string}
     * @memberof PlayerThemeCreationPayload
     */
    'name'?: string;
    /**
     * RGBA color for timer text. Default: rgba(255, 255, 255, 1)
     * @type {string}
     * @memberof PlayerThemeCreationPayload
     */
    'text'?: string;
    /**
     * RGBA color for all controls. Default: rgba(255, 255, 255, 1)
     * @type {string}
     * @memberof PlayerThemeCreationPayload
     */
    'link'?: string;
    /**
     * RGBA color for all controls when hovered. Default: rgba(255, 255, 255, 1)
     * @type {string}
     * @memberof PlayerThemeCreationPayload
     */
    'linkHover'?: string;
    /**
     * RGBA color for the play button when hovered.
     * @type {string}
     * @memberof PlayerThemeCreationPayload
     */
    'linkActive'?: string;
    /**
     * RGBA color playback bar: played content. Default: rgba(88, 131, 255, .95)
     * @type {string}
     * @memberof PlayerThemeCreationPayload
     */
    'trackPlayed'?: string;
    /**
     * RGBA color playback bar: downloaded but unplayed (buffered) content. Default: rgba(255, 255, 255, .35)
     * @type {string}
     * @memberof PlayerThemeCreationPayload
     */
    'trackUnplayed'?: string;
    /**
     * RGBA color playback bar: background. Default: rgba(255, 255, 255, .2)
     * @type {string}
     * @memberof PlayerThemeCreationPayload
     */
    'trackBackground'?: string;
    /**
     * RGBA color: top 50% of background. Default: rgba(0, 0, 0, .7)
     * @type {string}
     * @memberof PlayerThemeCreationPayload
     */
    'backgroundTop'?: string;
    /**
     * RGBA color: bottom 50% of background. Default: rgba(0, 0, 0, .7)
     * @type {string}
     * @memberof PlayerThemeCreationPayload
     */
    'backgroundBottom'?: string;
    /**
     * RGBA color for title text. Default: rgba(255, 255, 255, 1)
     * @type {string}
     * @memberof PlayerThemeCreationPayload
     */
    'backgroundText'?: string;
    /**
     * enable/disable player SDK access. Default: true
     * @type {boolean}
     * @memberof PlayerThemeCreationPayload
     */
    'enableApi'?: boolean;
    /**
     * enable/disable player controls. Default: true
     * @type {boolean}
     * @memberof PlayerThemeCreationPayload
     */
    'enableControls'?: boolean;
    /**
     * enable/disable player autoplay. Default: false
     * @type {boolean}
     * @memberof PlayerThemeCreationPayload
     */
    'forceAutoplay'?: boolean;
    /**
     * enable/disable title. Default: false
     * @type {boolean}
     * @memberof PlayerThemeCreationPayload
     */
    'hideTitle'?: boolean;
    /**
     * enable/disable looping. Default: false
     * @type {boolean}
     * @memberof PlayerThemeCreationPayload
     */
    'forceLoop'?: boolean;
}

