/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RestreamsResponseObject
 */
export interface RestreamsResponseObject {
    /**
     * Returns the name of a restream destination.
     * @type {string}
     * @memberof RestreamsResponseObject
     */
    'name'?: string;
    /**
     * Returns the RTMP URL of a restream destination.
     * @type {string}
     * @memberof RestreamsResponseObject
     */
    'serverUrl'?: string;
    /**
     * Returns the unique key of the live stream that is set up for restreaming.
     * @type {string}
     * @memberof RestreamsResponseObject
     */
    'streamKey'?: string;
}

