/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Adding restream destinations is optional. However, if you set a restream destination, you must provide all attributes for each destination.
 * @export
 * @interface RestreamsRequestObject
 */
export interface RestreamsRequestObject {
    /**
     * Use this parameter to define a name for the restream destination.
     * @type {string}
     * @memberof RestreamsRequestObject
     */
    'name': string;
    /**
     * Use this parameter to set the RTMP URL of the restream destination.
     * @type {string}
     * @memberof RestreamsRequestObject
     */
    'serverUrl': string;
    /**
     * Use this parameter to provide the unique key of the live stream that you want to restream.
     * @type {string}
     * @memberof RestreamsRequestObject
     */
    'streamKey': string;
}

