/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Pagination } from './pagination';
import { UploadToken } from './upload-token';

/**
 * 
 * @export
 * @interface TokenListResponse
 */
export interface TokenListResponse {
    /**
     * 
     * @type {Array<UploadToken>}
     * @memberof TokenListResponse
     */
    'data': Array<UploadToken>;
    /**
     * 
     * @type {Pagination}
     * @memberof TokenListResponse
     */
    'pagination': Pagination;
}

