/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Metadata } from './metadata';

/**
 * 
 * @export
 * @interface VideoSessionSession
 */
export interface VideoSessionSession {
    /**
     * The unique identifier for the session that you can use to track what happens during it.
     * @type {string}
     * @memberof VideoSessionSession
     */
    'sessionId'?: string;
    /**
     * When the video session started, presented in ISO-8601 format.
     * @type {string}
     * @memberof VideoSessionSession
     */
    'loadedAt'?: string;
    /**
     * When the video session ended, presented in ISO-8601 format.
     * @type {string}
     * @memberof VideoSessionSession
     */
    'endedAt'?: string;
    /**
     * A list of key value pairs that you use to provide metadata for your video. These pairs can be made dynamic, allowing you to segment your audience. You can also just use the pairs as another way to tag and categorize your videos.
     * @type {Array<Metadata>}
     * @memberof VideoSessionSession
     */
    'metadata'?: Array<Metadata>;
}

