/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VideoStatusEncoding } from './video-status-encoding';
import { VideoStatusIngest } from './video-status-ingest';

/**
 * 
 * @export
 * @interface VideoStatus
 */
export interface VideoStatus {
    /**
     * 
     * @type {VideoStatusIngest}
     * @memberof VideoStatus
     */
    'ingest'?: VideoStatusIngest;
    /**
     * 
     * @type {VideoStatusEncoding}
     * @memberof VideoStatus
     */
    'encoding'?: VideoStatusEncoding;
}

