/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VideoSessionReferrer
 */
export interface VideoSessionReferrer {
    /**
     * The link the viewer used to reach the video session.
     * @type {string}
     * @memberof VideoSessionReferrer
     */
    'url'?: string | null;
    /**
     * How they arrived at the site, for example organic or paid. Organic meaning they found it themselves and paid meaning they followed a link from an advertisement.
     * @type {string}
     * @memberof VideoSessionReferrer
     */
    'medium'?: string;
    /**
     * The source the referrer came from to the video session. For example if they searched through google to find the stream.
     * @type {string}
     * @memberof VideoSessionReferrer
     */
    'source'?: string;
    /**
     * The search term they typed to arrive at the video session.
     * @type {string}
     * @memberof VideoSessionReferrer
     */
    'searchTerm'?: string;
}

