/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VideoSourceLiveStreamLink } from './video-source-live-stream-link';

/**
 * This appears if the video is from a Live Record.
 * @export
 * @interface VideoSourceLiveStream
 */
export interface VideoSourceLiveStream {
    /**
     * The unique identifier for the live stream.
     * @type {string}
     * @memberof VideoSourceLiveStream
     */
    'liveStreamId'?: string;
    /**
     * 
     * @type {Array<VideoSourceLiveStreamLink>}
     * @memberof VideoSourceLiveStream
     */
    'links'?: Array<VideoSourceLiveStreamLink>;
}

