/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VideoStatusIngestReceivedParts
 */
export interface VideoStatusIngestReceivedParts {
    /**
     * The parts that have been uploaded, ordered. For example, if part 2 was sent before part 1, and both have been uploaded, the output will be [1, 2].
     * @type {Array<number>}
     * @memberof VideoStatusIngestReceivedParts
     */
    'parts'?: Array<number>;
    /**
     * Contains the number of expected parts. The total will be listed as \"null\" until the total number of parts is known.
     * @type {number}
     * @memberof VideoStatusIngestReceivedParts
     */
    'total'?: number | null;
}

