/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VideoWatermark
 */
export interface VideoWatermark {
    /**
     * id of the watermark
     * @type {string}
     * @memberof VideoWatermark
     */
    'id'?: string;
    /**
     * Distance expressed in px or % between the top-border of the video and the watermark-image.
     * @type {string}
     * @memberof VideoWatermark
     */
    'top'?: string;
    /**
     * Distance expressed in px or % between the left-border of the video and the watermark-image.
     * @type {string}
     * @memberof VideoWatermark
     */
    'left'?: string;
    /**
     * Distance expressed in px or % between the bottom-border of the video and the watermark-image.
     * @type {string}
     * @memberof VideoWatermark
     */
    'bottom'?: string;
    /**
     * Distance expressed in px or % between the right-border of the video and the watermark-image.
     * @type {string}
     * @memberof VideoWatermark
     */
    'right'?: string;
    /**
     * Width of the watermark-image relative to the video if expressed in %. Otherwise a fixed width. NOTE: To keep intrinsic watermark-image width use `initial`.
     * @type {string}
     * @memberof VideoWatermark
     */
    'width'?: string;
    /**
     * Height of the watermark-image relative to the video if expressed in %. Otherwise a fixed height. NOTE: To keep intrinsic watermark-image height use `initial`.
     * @type {string}
     * @memberof VideoWatermark
     */
    'height'?: string;
    /**
     * Opacity expressed in % only to specify the degree of the watermark-image transparency with the video.
     * @type {string}
     * @memberof VideoWatermark
     */
    'opacity'?: string;
}

