/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BytesRange } from './bytes-range';
import { VideoStatusIngestReceivedParts } from './video-status-ingest-received-parts';

/**
 * Details about the capturing, transferring, and storing of your video for use immediately or in the future.
 * @export
 * @interface VideoStatusIngest
 */
export interface VideoStatusIngest {
    /**
     * There are four possible statuses depending on how you provide a video file: - `uploading` - the API is gathering the video source file from an upload. - `uploaded` - the video file is fully uploaded. - `ingesting` - the API is gathering the video source file from either a URL, or from cloning. - `ingested` - the video file is fully stored. 
     * @type {string}
     * @memberof VideoStatusIngest
     */
    'status'?: VideoStatusIngestStatusEnum;
    /**
     * The size of your file in bytes.
     * @type {number}
     * @memberof VideoStatusIngest
     */
    'filesize'?: number | null;
    /**
     * The total number of bytes received, listed for each chunk of the upload.
     * @type {Array<BytesRange>}
     * @memberof VideoStatusIngest
     */
    'receivedBytes'?: Array<BytesRange>;
    /**
     * 
     * @type {VideoStatusIngestReceivedParts}
     * @memberof VideoStatusIngest
     */
    'receivedParts'?: VideoStatusIngestReceivedParts;
}

type VideoStatusIngestStatusEnum = 'uploading' | 'uploaded' | 'ingesting' | 'ingested'


