/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VideoSessionClient } from './video-session-client';
import { VideoSessionDevice } from './video-session-device';
import { VideoSessionLocation } from './video-session-location';
import { VideoSessionOs } from './video-session-os';
import { VideoSessionReferrer } from './video-session-referrer';
import { VideoSessionSession } from './video-session-session';

/**
 * 
 * @export
 * @interface VideoSession
 */
export interface VideoSession {
    /**
     * 
     * @type {VideoSessionSession}
     * @memberof VideoSession
     */
    'session'?: VideoSessionSession;
    /**
     * 
     * @type {VideoSessionLocation}
     * @memberof VideoSession
     */
    'location'?: VideoSessionLocation;
    /**
     * 
     * @type {VideoSessionReferrer}
     * @memberof VideoSession
     */
    'referrer'?: VideoSessionReferrer;
    /**
     * 
     * @type {VideoSessionDevice}
     * @memberof VideoSession
     */
    'device'?: VideoSessionDevice;
    /**
     * 
     * @type {VideoSessionOs}
     * @memberof VideoSession
     */
    'os'?: VideoSessionOs;
    /**
     * 
     * @type {VideoSessionClient}
     * @memberof VideoSession
     */
    'client'?: VideoSessionClient;
}

