/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Quality } from './quality';
import { VideoStatusEncodingMetadata } from './video-status-encoding-metadata';

/**
 * 
 * @export
 * @interface VideoStatusEncoding
 */
export interface VideoStatusEncoding {
    /**
     * Whether the video is playable or not.
     * @type {boolean}
     * @memberof VideoStatusEncoding
     */
    'playable'?: boolean;
    /**
     * Available qualities the video can be viewed in.
     * @type {Array<Quality>}
     * @memberof VideoStatusEncoding
     */
    'qualities'?: Array<Quality>;
    /**
     * 
     * @type {VideoStatusEncodingMetadata}
     * @memberof VideoStatusEncoding
     */
    'metadata'?: VideoStatusEncodingMetadata;
}

