/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Metadata } from './metadata';
import { VideoClip } from './video-clip';
import { VideoWatermark } from './video-watermark';

/**
 * 
 * @export
 * @interface VideoCreationPayload
 */
export interface VideoCreationPayload {
    /**
     * A list of tags you want to use to describe your video.
     * @type {Array<string>}
     * @memberof VideoCreationPayload
     */
    'tags'?: Array<string>;
    /**
     * The title of your new video.
     * @type {string}
     * @memberof VideoCreationPayload
     */
    'title': string;
    /**
     * A brief description of your video.
     * @type {string}
     * @memberof VideoCreationPayload
     */
    'description'?: string;
    /**
     * You can either add a video already on the web, by entering the URL of the video, or you can also enter the `videoId` of one of the videos you already have on your api.video acccount, and this will generate a copy of your video. Creating a copy of a video can be especially useful if you want to keep your original video and trim or apply a watermark onto the copy you would create.
     * @type {string}
     * @memberof VideoCreationPayload
     */
    'source'?: string;
    /**
     * Default: True. If set to `false` the video will become private. More information on private videos can be found [here](https://docs.api.video/delivery-analytics/video-privacy-access-management)
     * @type {boolean}
     * @memberof VideoCreationPayload
     */
    'public'?: boolean;
    /**
     * Indicates if your video is a 360/immersive video.
     * @type {boolean}
     * @memberof VideoCreationPayload
     */
    'panoramic'?: boolean;
    /**
     * Enables mp4 version in addition to streamed version.
     * @type {boolean}
     * @memberof VideoCreationPayload
     */
    'mp4Support'?: boolean;
    /**
     * The unique identification number for your video player.
     * @type {string}
     * @memberof VideoCreationPayload
     */
    'playerId'?: string;
    /**
     * A list of key value pairs that you use to provide metadata for your video. These pairs can be made dynamic, allowing you to segment your audience. Read more on [dynamic metadata](https://api.video/blog/endpoints/dynamic-metadata/).
     * @type {Array<Metadata>}
     * @memberof VideoCreationPayload
     */
    'metadata'?: Array<Metadata>;
    /**
     * 
     * @type {VideoClip}
     * @memberof VideoCreationPayload
     */
    'clip'?: VideoClip;
    /**
     * 
     * @type {VideoWatermark}
     * @memberof VideoCreationPayload
     */
    'watermark'?: VideoWatermark;
}

