/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VideoSourceLiveStream } from './video-source-live-stream';

/**
 * Source information about the video.
 * @export
 * @interface VideoSource
 */
export interface VideoSource {
    /**
     * The URL where the video is stored.
     * @type {string}
     * @memberof VideoSource
     */
    'uri'?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoSource
     */
    'type'?: string;
    /**
     * 
     * @type {VideoSourceLiveStream}
     * @memberof VideoSource
     */
    'liveStream'?: VideoSourceLiveStream;
}

