/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The operating system the viewer is on.
 * @export
 * @interface VideoSessionOs
 */
export interface VideoSessionOs {
    /**
     * The version of the operating system.
     * @type {string}
     * @memberof VideoSessionOs
     */
    'version'?: string;
    /**
     * The name of the operating system.
     * @type {string}
     * @memberof VideoSessionOs
     */
    'name'?: string;
    /**
     * The nickname for the operating system, often representing the version.
     * @type {string}
     * @memberof VideoSessionOs
     */
    'shortname'?: string;
}

