/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The location of the viewer.
 * @export
 * @interface VideoSessionLocation
 */
export interface VideoSessionLocation {
    /**
     * The country of the viewer.
     * @type {string}
     * @memberof VideoSessionLocation
     */
    'country'?: string;
    /**
     * The city of the viewer.
     * @type {string}
     * @memberof VideoSessionLocation
     */
    'city'?: string | null;
}

