/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Watermark
 */
export interface Watermark {
    /**
     * The unique identifier of the watermark.
     * @type {string}
     * @memberof Watermark
     */
    'watermarkId'?: string;
    /**
     * When the watermark was created, presented in ISO-8601 format.
     * @type {string}
     * @memberof Watermark
     */
    'createdAt'?: string;
}

