/*
api.video

api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.

The version of the OpenAPI document: 1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Pagination } from './pagination';
import { Webhook } from './webhook';

/**
 * 
 * @export
 * @interface WebhooksListResponse
 */
export interface WebhooksListResponse {
    /**
     * 
     * @type {Array<Webhook>}
     * @memberof WebhooksListResponse
     */
    'data': Array<Webhook>;
    /**
     * 
     * @type {Pagination}
     * @memberof WebhooksListResponse
     */
    'pagination': Pagination;
}

